"""create players games guesses tables

Revision ID: 81ae03297bf9
Revises:
Create Date: 2026-03-27 20:22:25.313875

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "81ae03297bf9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
